<template>
  <div :class="$style.dashboard">
    <Header />

    <!-- 待核验热点面板 -->
    <VerificationPanel />

    <div :class="$style.main">
      <MarketSelector />

      <div :class="$style.content">
        <!-- 时间旅行滑块 -->
        <TimelineSlider />

        <!-- 当前拦截信息 -->
        <div :class="$style.section">
          <div :class="$style.sectionTitle">
            当前分析热点: <span :class="$style.highlight">{{ displayTrendName }}</span>
            <span :class="$style.updateInfo">{{ currentMarketName }} · {{ currentTierName }}</span>
          </div>

          <div :class="$style.cards">
            <BriefingCard
              number="指标 01:"
              title="热度评分"
              :score="displayScore"
              subtitle="综合评估分数"
              :description="`当前评分 ${displayScore}/100，${displayStatus}`"
            />
            <BriefingCard
              number="指标 02:"
              title="穿戴转化率"
              :score="displayWearRate"
              subtitle="真实佩戴场景验证"
              :description="`穿戴转化率 ${displayWearRate}%，真实用户持续增长`"
            />
            <BriefingCard
              number="指标 03:"
              title="社交声量"
              :score="92"
              subtitle="社交媒体影响力"
              :description="`社交声量 ${displaySocialVolume}，${displayCategory}`"
            />
          </div>
        </div>

        <!-- 实时信息流和简报 -->
        <div :class="$style.bottomSection">
          <div :class="$style.feedSection">
            <LiveFeed @stats="onFeedStats" />
          </div>

          <div :class="$style.briefingSection">
            <div :class="$style.briefingHeader">
              <div :class="$style.briefingTitle">● DAILY STRATEGIC BRIEFING</div>
              <div :class="$style.autoGenerated">AUTO-GENERATED</div>
            </div>

            <div :class="$style.briefingContent">
              <div :class="$style.briefingItem">
                <div :class="$style.briefingNumber">01.</div>
                <div :class="$style.briefingText">
                  <div :class="$style.briefingLabel">热点分类 (CATEGORY)</div>
                  <p>{{ displayCategory }}</p>
                </div>
              </div>

              <div :class="$style.briefingItem">
                <div :class="$style.briefingNumber">02.</div>
                <div :class="$style.briefingText">
                  <div :class="$style.briefingLabel">关键洞察 (KEY INSIGHTS)</div>
                  <div :class="$style.highlight2">核心发现</div>
                  <p>{{ displayKeyInsights }}</p>
                </div>
              </div>

              <div :class="$style.briefingItem">
                <div :class="$style.briefingNumber">03.</div>
                <div :class="$style.briefingText">
                  <div :class="$style.briefingLabel">建议行动 (RECOMMENDATION)</div>
                  <p>{{ displayRecommendation }}</p>
                </div>
              </div>

              <div :class="$style.briefingItem">
                <div :class="$style.briefingNumber">04.</div>
                <div :class="$style.briefingText">
                  <div :class="$style.briefingLabel">跨境营销工具 (AI MARKETING KIT)</div>
                  <div :class="$style.toolButtons">
                    <button :class="$style.toolBtn">一键生成TikTok带货案</button>
                    <button :class="$style.toolBtn">一键生成Midjourney Prompt</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Agent 3 对话 -->
    <ChatButton />
    <ChatPanel />
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { storeToRefs } from 'pinia'
import { useMarketStore } from '@/stores/market'
import Header from '@/components/layout/Header.vue'
import MarketSelector from '@/components/layout/MarketSelector.vue'
import BriefingCard from '@/components/briefing/BriefingCard.vue'
import LiveFeed from '@/components/briefing/LiveFeed.vue'
import TimelineSlider from '@/components/briefing/TimelineSlider.vue'
import VerificationPanel from '@/components/briefing/VerificationPanel.vue'
import ChatButton from '@/components/chat/ChatButton.vue'
import ChatPanel from '@/components/chat/ChatPanel.vue'

const marketStore = useMarketStore()
const { selectedTrend, currentMarketName, currentTierName } = storeToRefs(marketStore)

const feedStats = ref({})

function onFeedStats(stats) {
  feedStats.value = stats || {}
}

const filterRateDisplay = computed(() => {
  const rate = feedStats.value?.filter_rate
  if (rate === undefined || rate === null) return '—'
  return `${rate}%`
})

// 根据选中的热点动态显示数据
const displayTrendName = computed(() => {
  return selectedTrend.value?.name || '#CHIIKAWA 错综复杂与日常黄金金饰'
})

const displayCategory = computed(() => {
  return selectedTrend.value?.category || 'IP联名×轻量化金饰'
})

const displayScore = computed(() => {
  return selectedTrend.value?.current_score || 89
})

const displayWearRate = computed(() => {
  return selectedTrend.value?.wear_conversion_rate || 78.2
})

const displaySocialVolume = computed(() => {
  return selectedTrend.value?.social_volume || '15.3K'
})

const displayKeyInsights = computed(() => {
  return selectedTrend.value?.key_insights || '情绪陪伴型IP与轻量化金饰的完美结合，穿戴转化率持续上升'
})

const displayRecommendation = computed(() => {
  return selectedTrend.value?.recommendation || '建议启动联名合作，重点投入'
})

const displayStatus = computed(() => {
  return selectedTrend.value?.status || '长线资产确认'
})
</script>

<style module>
.dashboard {
  min-height: 100vh;
  background: #0a0a0a;
  color: #fff;
}

.main {
  display: flex;
  height: calc(100vh - 60px);
}

.content {
  flex: 1;
  padding: 24px;
  overflow-y: auto;
}

.section {
  margin-bottom: 24px;
}

.sectionTitle {
  color: #d4af37;
  font-size: 13px;
  font-weight: 600;
  margin-bottom: 16px;
  display: flex;
  align-items: center;
  gap: 12px;
}

.highlight {
  color: #fff;
}

.updateInfo {
  color: #666;
  font-size: 11px;
  margin-left: auto;
}

.cards {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
}

.bottomSection {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24px;
}

.feedSection {
  min-height: 400px;
}

.briefingSection {
  background: #0a0a0a;
  border: 1px solid #333;
  border-radius: 8px;
  padding: 20px;
}

.briefingHeader {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding-bottom: 12px;
  border-bottom: 1px solid #333;
}

.briefingTitle {
  color: #4ade80;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 2px;
}

.autoGenerated {
  color: #666;
  font-size: 10px;
  padding: 4px 8px;
  background: #111;
  border-radius: 3px;
}

.briefingContent {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.briefingItem {
  display: flex;
  gap: 12px;
}

.briefingNumber {
  color: #d4af37;
  font-size: 14px;
  font-weight: 600;
  flex-shrink: 0;
}

.briefingText {
  flex: 1;
}

.briefingLabel {
  color: #999;
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  margin-bottom: 8px;
}

.briefingText p {
  color: #ccc;
  font-size: 13px;
  line-height: 1.6;
  margin: 0 0 8px 0;
}

.briefingText ul {
  color: #ccc;
  font-size: 13px;
  line-height: 1.6;
  margin: 0;
  padding-left: 20px;
}

.briefingText li {
  margin-bottom: 4px;
}

.highlight2 {
  display: inline-block;
  color: #d4af37;
  font-size: 11px;
  font-weight: 600;
  padding: 2px 8px;
  background: rgba(212, 175, 55, 0.1);
  border-radius: 3px;
  margin-bottom: 8px;
}

.toolButtons {
  display: flex;
  gap: 8px;
  margin-top: 8px;
}

.toolBtn {
  background: linear-gradient(135deg, #d4af37 0%, #b8941f 100%);
  border: none;
  border-radius: 4px;
  padding: 8px 16px;
  color: #000;
  font-size: 11px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.toolBtn:hover {
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(212, 175, 55, 0.3);
}

.agentStatus {
  position: fixed;
  bottom: 32px;
  left: 32px;
  background: #111;
  border: 1px solid #333;
  border-radius: 8px;
  padding: 16px;
  min-width: 280px;
  max-width: 320px;
}

.statusTitle {
  color: #d4af37;
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 1px;
  margin-bottom: 12px;
  padding-bottom: 8px;
  border-bottom: 1px solid #222;
}

.gateSection {
  margin-bottom: 12px;
  padding: 8px;
  background: #0a0a0a;
  border-radius: 4px;
}

.gateTitle {
  color: #4ade80;
  font-size: 10px;
  font-weight: 600;
  margin-bottom: 6px;
}

.statusItem {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 4px;
  font-size: 10px;
}

.statusLabel {
  color: #999;
}

.statusValue {
  color: #4ade80;
  font-weight: 600;
  font-size: 9px;
  padding: 2px 6px;
  background: rgba(74, 222, 128, 0.1);
  border-radius: 2px;
}

.statusSummary {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-top: 8px;
  border-top: 1px solid #222;
  margin-top: 8px;
}

.summaryLabel {
  color: #d4af37;
  font-size: 11px;
  font-weight: 600;
}

.summaryValue {
  color: #d4af37;
  font-size: 14px;
  font-weight: 700;
}

/* 响应式 */
@media (max-width: 1400px) {
  .cards {
    grid-template-columns: 1fr;
  }

  .bottomSection {
    grid-template-columns: 1fr;
  }
}
</style>
