<template>
  <div :class="$style.dashboard">
    <Header />

    <!-- 待核验热点面板 -->
    <VerificationPanel />

    <div :class="$style.main">
      <MarketSelector />

      <div :class="$style.content">
        <!-- 时间旅行滑块 -->
        <TimelineSlider />

        <!-- 当前拦截信息 -->
        <div :class="$style.section">
          <div :class="$style.sectionTitle">
            当前拦截信息: <span :class="$style.highlight">#CHIIKAWA 错综复杂与日常黄金金饰</span>
            <span :class="$style.updateInfo">更新频次: 实时 (Live Search API Bound)</span>
          </div>

          <div :class="$style.cards">
            <BriefingCard
              number="阀门 01:"
              title="历史流速基准 (Pass)"
              :score="89"
              subtitle="双时间窗分析: 历史流速基准通过"
              description="月、发展趋势稳定且具有长线活跃度。ACGN×奢侈品，非单次爆发性话题，具备长线活跃度。"
            />
            <BriefingCard
              number="阀门 02:"
              title="社交声量验证 (Pass)"
              :score="96.4"
              subtitle="语义过滤: 自动过滤水军对立"
              description="核心互动率100%数据干净，核心互动率和机器人账号公关水军，核心互动率100%数据干净。"
            />
            <BriefingCard
              number="阀门 03:"
              title="穿戴外露验证 (High)"
              :score="92"
              subtitle="行为特征码: 真实佩戴场景验证"
              description="触发行为特征码校验，真实佩戴场景验证通过。"
            />
          </div>
        </div>

        <!-- 实时信息流和简报 -->
        <div :class="$style.bottomSection">
          <div :class="$style.feedSection">
            <LiveFeed />
          </div>

          <div :class="$style.briefingSection">
            <div :class="$style.briefingHeader">
              <div :class="$style.briefingTitle">● DAILY STRATEGIC BRIEFING</div>
              <div :class="$style.autoGenerated">AUTO-GENERATED</div>
            </div>

            <div :class="$style.briefingContent">
              <div :class="$style.briefingItem">
                <div :class="$style.briefingNumber">01.</div>
                <div :class="$style.briefingText">
                  <div :class="$style.briefingLabel">核心变化趋势 (KEY MARKET SHIFT)</div>
                  <p>目标出海市场Z世代-乙女体系传统金饰"宏大叙事"正加速向"微小叙事"转移。</p>
                </div>
              </div>

              <div :class="$style.briefingItem">
                <div :class="$style.briefingNumber">02.</div>
                <div :class="$style.briefingText">
                  <div :class="$style.briefingLabel">业务消费影响 (BUSINESS IMPACT)</div>
                  <div :class="$style.highlight2">机会</div>
                  <p>企业可直接跳过选品调研环节，重新锁定爆款的总价，轻量化定价策略。</p>
                </div>
              </div>

              <div :class="$style.briefingItem">
                <div :class="$style.briefingNumber">03.</div>
                <div :class="$style.briefingText">
                  <div :class="$style.briefingLabel">建议后续行动 (ACTIONABLE INSIGHTS)</div>
                  <ul>
                    <li>长期跟踪建议: 海外潮AI Marketing团队在未来3周内，数据包文件夹中，将Brand Voice调整为"目标性格"，提高15%。</li>
                    <li>短期启动活动: 立即启动"微小叙事"主题营销活动。</li>
                  </ul>
                </div>
              </div>

              <div :class="$style.briefingItem}>
                <div :class="$style.briefingNumber">04.</div>
                <div :class="$style.briefingText">
                  <div :class="$style.briefingLabel">跨境营销工具 (AI MARKETING KIT)</div>
                  <div :class="$style.toolButtons">
                    <button :class="$style.toolBtn">一键生成TikTok带货案</button>
                    <button :class="$style.toolBtn">一键生成Midjourney Prompt</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Agent 3 对话 -->
    <ChatButton />
    <ChatPanel />

    <!-- Agent Pipeline 状态 - 双重门控 -->
    <div :class="$style.agentStatus">
      <div :class="$style.statusTitle">🛡️ DUAL-GATE DE-NOISING SYSTEM</div>

      <div :class="$style.gateSection">
        <div :class="$style.gateTitle">第一道门: 结构化特征硬过滤</div>
        <div :class="$style.statusItem">
          <span :class="$style.statusLabel">强商业导向词过滤:</span>
          <span :class="$style.statusValue">ACTIVE</span>
        </div>
        <div :class="$style.statusItem">
          <span :class="$style.statusLabel">Hashtag滥用检测:</span>
          <span :class="$style.statusValue">ACTIVE</span>
        </div>
      </div>

      <div :class="$style.gateSection">
        <div :class="$style.gateTitle">第二道门: LLM语义纹理审计</div>
        <div :class="$style.statusItem">
          <span :class="$style.statusLabel">公式化通稿过滤:</span>
          <span :class="$style.statusValue">RUNNING</span>
        </div>
        <div :class="$style.statusItem">
          <span :class="$style.statusLabel">实体外露行为校验:</span>
          <span :class="$style.statusValue">RUNNING</span>
        </div>
      </div>

      <div :class="$style.statusSummary">
        <span :class="$style.summaryLabel">本轮过滤率:</span>
        <span :class="$style.summaryValue">87.3%</span>
      </div>
    </div>
  </div>
</template>

<script setup>
import Header from '@/components/layout/Header.vue'
import MarketSelector from '@/components/layout/MarketSelector.vue'
import BriefingCard from '@/components/briefing/BriefingCard.vue'
import LiveFeed from '@/components/briefing/LiveFeed.vue'
import TimelineSlider from '@/components/briefing/TimelineSlider.vue'
import VerificationPanel from '@/components/briefing/VerificationPanel.vue'
import ChatButton from '@/components/chat/ChatButton.vue'
import ChatPanel from '@/components/chat/ChatPanel.vue'
</script>

<style module>
.dashboard {
  min-height: 100vh;
  background: #0a0a0a;
  color: #fff;
}

.main {
  display: flex;
  height: calc(100vh - 60px);
}

.content {
  flex: 1;
  padding: 24px;
  overflow-y: auto;
}

.section {
  margin-bottom: 24px;
}

.sectionTitle {
  color: #d4af37;
  font-size: 13px;
  font-weight: 600;
  margin-bottom: 16px;
  display: flex;
  align-items: center;
  gap: 12px;
}

.highlight {
  color: #fff;
}

.updateInfo {
  color: #666;
  font-size: 11px;
  margin-left: auto;
}

.cards {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
}

.bottomSection {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24px;
}

.feedSection {
  min-height: 400px;
}

.briefingSection {
  background: #0a0a0a;
  border: 1px solid #333;
  border-radius: 8px;
  padding: 20px;
}

.briefingHeader {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding-bottom: 12px;
  border-bottom: 1px solid #333;
}

.briefingTitle {
  color: #4ade80;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 2px;
}

.autoGenerated {
  color: #666;
  font-size: 10px;
  padding: 4px 8px;
  background: #111;
  border-radius: 3px;
}

.briefingContent {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.briefingItem {
  display: flex;
  gap: 12px;
}

.briefingNumber {
  color: #d4af37;
  font-size: 14px;
  font-weight: 600;
  flex-shrink: 0;
}

.briefingText {
  flex: 1;
}

.briefingLabel {
  color: #999;
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  margin-bottom: 8px;
}

.briefingText p {
  color: #ccc;
  font-size: 13px;
  line-height: 1.6;
  margin: 0 0 8px 0;
}

.briefingText ul {
  color: #ccc;
  font-size: 13px;
  line-height: 1.6;
  margin: 0;
  padding-left: 20px;
}

.briefingText li {
  margin-bottom: 4px;
}

.highlight2 {
  display: inline-block;
  color: #d4af37;
  font-size: 11px;
  font-weight: 600;
  padding: 2px 8px;
  background: rgba(212, 175, 55, 0.1);
  border-radius: 3px;
  margin-bottom: 8px;
}

.toolButtons {
  display: flex;
  gap: 8px;
  margin-top: 8px;
}

.toolBtn {
  background: linear-gradient(135deg, #d4af37 0%, #b8941f 100%);
  border: none;
  border-radius: 4px;
  padding: 8px 16px;
  color: #000;
  font-size: 11px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.toolBtn:hover {
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(212, 175, 55, 0.3);
}

.agentStatus {
  position: fixed;
  bottom: 32px;
  left: 32px;
  background: #111;
  border: 1px solid #333;
  border-radius: 8px;
  padding: 16px;
  min-width: 280px;
  max-width: 320px;
}

.statusTitle {
  color: #d4af37;
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 1px;
  margin-bottom: 12px;
  padding-bottom: 8px;
  border-bottom: 1px solid #222;
}

.gateSection {
  margin-bottom: 12px;
  padding: 8px;
  background: #0a0a0a;
  border-radius: 4px;
}

.gateTitle {
  color: #4ade80;
  font-size: 10px;
  font-weight: 600;
  margin-bottom: 6px;
}

.statusItem {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 4px;
  font-size: 10px;
}

.statusLabel {
  color: #999;
}

.statusValue {
  color: #4ade80;
  font-weight: 600;
  font-size: 9px;
  padding: 2px 6px;
  background: rgba(74, 222, 128, 0.1);
  border-radius: 2px;
}

.statusSummary {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-top: 8px;
  border-top: 1px solid #222;
  margin-top: 8px;
}

.summaryLabel {
  color: #d4af37;
  font-size: 11px;
  font-weight: 600;
}

.summaryValue {
  color: #d4af37;
  font-size: 14px;
  font-weight: 700;
}

/* 响应式 */
@media (max-width: 1400px) {
  .cards {
    grid-template-columns: 1fr;
  }

  .bottomSection {
    grid-template-columns: 1fr;
  }
}
</style>
